#+STARTUP: indent
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+TITLE:     UniDB Performance and Application Specific Databases
#+AUTHOR:    John Brestelli
#+DESCRIPTION: How to solve performance issues with Genomics websites by building Application Specific Databases
#+OPTIONS:   H:5 num:nil toc:3 p:t tags:not-in-toc eval:never-export
#+STARTUP: overview
* Website Performance

[[https://drive.google.com/drive/u/2/folders/1IEnXB5j2Emw46-dGyZRs3P-wIZNSVEON][Performance Testing revealed]] general poor performance of the unified database.  In addition, there were several very poor performing tools.  Each area of concern is listed below and proposed solutions if needed.  The general strategy for fixing the website performance will be:
1. Focus initially on worst performers.
2. Use holistic approach to performance tuning.  (tuning for a data type not a specific tool)
3. Duplicate data as needed to speed up applications
   - Eliminate big complicated queries in the application.  Create more de normalized tables
   - nosql database where appropriate (site search, record pages?)
   - flat file stores for genome browsers


A summary of the details below can be found in [[https://docs.google.com/spreadsheets/d/1JF7MZ8cXjua9h0mMRNb3TkfuXjczI0Pl64yXqOJDXOo/edit#gid=358028577][Google Docs]]
  
** WDK Searches
*** REST Search Result  / ID Query :JohnB:JohnI:MarkH:
- GOAL :: as good as portal/or plasmo and < 1.5 seconds

- SOLUTION :: Use holistic approach to create new denormalized tables or add indexes to existing tables.  This will allow us to replace big queries which have many joins.  Each search will be evaluated and fixed as required.  Search id query, param queries, record table and possibly pbrowse track data should be gotten with smallest table joins (one table properly indexed if possible)
  - current model uses lots of tables from normalized schemas
    | *Schema*    | *Notes*                                                     |
    |-------------+-------------------------------------------------------------|
    | ApiDBTuning | remove fk to other schemas                                  |
    | ApidB       | can we retain these or do we need to move to tuning tables? |
    | DoTS        | Do not use in the website application                       |
    | Sres        | Do not use in the website application                       |
    | Core        | Do not use in the website application                       |
    | chebi       | ok                                                          |
    | hmdb        | ok                                                          |
    | platform    | can we retain these or do we need to copy to tuning tables? |
    | Results     | can we retain these or do we need to copy to tuning tables? |
    | Study       | replace with EDA                                            |

- COST :: few days per datatype (example interpro tuningtable,search,params,pbrowse,wdkTable took 3 days 1 fte)
  
*** Results Page Completion :Steve:Cristina:
- GOAL :: as good as portal/or plasmo and < 1.5 seconds
- SOLUTION :: There are [[https://docs.google.com/spreadsheets/d/1JF7MZ8cXjua9h0mMRNb3TkfuXjczI0Pl64yXqOJDXOo/edit#gid=2056082386][several queries]] which are run to make search results.  gene results are made worse because we insert transcripts which don't match the result.  Some possible solutions here are:
  1. General wdk performance improvements including column filters.
     - Filter perforamnce depends on result size.
     - the biggy:  doing the group by, to transfer a distribution, not all raw data
     - getting rid of slow single-gene filter
     - using a dedicated, skinny, attribute table to get the organism
  2. Preview results instead directly going to results page

- COST :: TODO Steve


*** Join To Attributes / Columns :Steve:Cristina:
- GOAL :: as good as portal/or plasmo

- SOLUTION :: On beta.veupathdb.org there are two issues we need to address:
  1. 10K columns (bad response time and bad ux)
     - this can be greatly ameliorated by dave's idea of filtering them based on the organisms in the result.  would require some wiring
  2. the cost of joining large results to large attribute queries
     - Need to demonstrate this as a problem

- COST :: TODO Steve

*** Download Results :Steve:Cristina:
- GOAL :: TBD

- SOLUTION :: Download seems like an area we have some flexibility if the user was made to understand this was a long running process (like multiblast).  Nothing to be done in the short term but long term could consider queue system like multiblast.  

- COST :: TODO Steve

- NOTE :: For the Download Page Form ... The large number of columns is an issue here too.  10K columns most from trasncriptomics datasets.  Same solution as above can be applied here.  Trim by organisms in result set

*** Search Page Load (Parameters) :JohnB:JohnI:MarkH:
- GOAL :: Vocab queries are cached;  All params on a search page should load < 5 seconds on initial run.

- SOLUTION :: Same as ID Searches above.  Use holistic approach to create new denormalized tables or add indexes to existing tables.  This will allow us to replace big queries which have many joins.  Each search will be evaluated and fixed as required.

- COST :: few days per datatype (example interpro tuningtable,search,params,pbrowse,wdkTable took 3 days 1 fte)

*** TODO Analysis Tools (example: GO Enrichment)
** WDK Records
*** Individual Tables :JohnB:JohnI:MarkH:
 - GOAL :: as good as plasmo ( < 1 seconds)

- SOLUTION :: Same as ID Searches above.  Use holistic approach to create new denormalized tables or add indexes to existing tables.  This will allow us to replace big queries which have many joins.  Each search will be evaluated and fixed as required.

- COST :: few days per datatype (example interpro tuningtable,search,params,pbrowse,wdkTable took 3 days 1 fte)

*** Initial Page Load :JohnB:JohnI:MarkH:
- GOAL :: as good as plasmo ( < 5 seconds)

- SOLUTION :: Some improvements have already been made here for the GeneRecord page.  We are likely under 5 seconds for initial page load assuming only record overview is open.  We identified some record interal tables which were poor performing and fixed including (FungiDB specific Linkouts in the overview section).  We also need to evaluate examples from all record types to ensure we are < 5 seconds for each.

*** Full Page Load
- GOAL :: TBD

- SOLUTION :: In the future we could explore caching all record tables/attributes in a nosql database.  JBrowse and DataPlotter graphs would still be loaded as they are now but tables and attributes would be loaded very quickly.

** Genome and Protein Browsers :JohnI:JohnB:
[[orgdocs:/SOPs/jbrowseFlatFileMigration.html][JBrowse Migration]]

*** Initial Page Load :JohnB:JohnI:MarkH:

- GOAL :: < 5 seconds

- SOLUTION :: There are 2 areas we can explore:
  1. We currently use webservice calls to create configuration of jbrwose tracks per organism.
     - We currently cache only some of these but we can explore caching all of them
  2. For organisms with a lot of functional data (RNASeq) those configurations are large and take a long time (5-7 seconds) to load
     - Need to explore if this is related to #1 or if the files can be made smaller

- COST :: If the size of the config file is truly probelmatic... would need to explore some sort of lazy loading mechanism which is costly as it would be a jbrowse appliation feature.

*** Individual Tracks :JohnB:JohnI:MarkH:
- GOAL :: < 1 seconds

- SOLUTION :: JBrowse is meant to be use files as data stores.  We currently use a REST store which queries the GUS Database for many of the tracks.  We can update the ReFlow workflow to dump gff files for all tracks which currently use the REST Store.  Popups can use web service calls (wdk record tables and attributes).

- COST :: There are 30 Genome Queries and ~ 10 PBrowse Queries which we need to update (few weeks effort).  The data loaders would need to create the files in webservices.  The Synteny Track and Intron Junctions are problematic.  For junctions, we need to move data out of tuning manager and into the workflow (high cost; ask Brian).  For Synteny we need to write a custom endpoint which would do the scaling for the visible region.  that is currently being done in sql. Lastly, we would need to change the way we search for genes within jbrowse application.  Currently this is done with another REST service but we'd need to do this from files.

- NOTE :: Even thought this is a big cost, there are some other advantages to doing this:  
  - it would simplify Apollo
  - allow us to run one JBrowse instead of one per site
  - could run JBrowse2 from the same files

*** Gene Page Context (iframes) :JohnB:JohnI:MarkH:

- GOAL :: iframes load the entire application so the initial load will not be faster than time to load jbrowse

- SOLUTION :: We already limit the configurations per section.  Ideally each section would only know about the tracks we display in that section but for some sections we are loading more than needed.

- COST :: Refactoring JBRowse configurations per organism could be done as part of the ReFlow steps above.
** MapVEu Application :BobM:Jay:JohnB:
This will be an EDA Application.  Those tables have been optimized for study data.  We may need to address special issues as they arise
** TODO Sequence Retrieval Tool 
** TODO MultiBLAST :Steve:Cristina:
** DONE Site Search
- GOAL :: as good as portal/plasmo ( < 1.5 seconds)
** DONE Home Page
- GOAL :: as good as portal/plasmo ( < 5 slower)

* Data Loading :JohnB:JohnI:Wei:
The Goal is to Shorten the Loading time
** Reflow workflow
- use the tuning manager (or other mechanism) to create organism specific tables as the last step in the organism workflow
  - The tuning manager is already able to make organism specific tables
    #+begin_src example
    apidbtuning.pfal3d7_interprodomains1234
    #+end_src
- This step should be fairly stable.  Should only be rerun when organism is undone/ reloaded or global data like GO terms/taxonomy refreshed
- The resulting tuning tables should be self contained
  - [ ] remove any GUS ids (fks to non apidbtuning tables)
- The Build databases can be any number of organisms.  One organism to all organisms
  - component dbs currently control pairwise syntenic alignments
- On this model it doesn't matter how many organisms are loaded into each build instance.  However, the data load team has been hitting issues with Undo
- can we partition by Row_Alg_invocation_id ? (after postgres migration)
  - The Undo mechanism we have in place could drop the partition instead of deleting the rows.
** Tuning Manager
- still need a tuning job for dataset presenters and other global dbs
- tuning job (post reflow) would continue to be quick/dirty way to add features until full reflow wf can be run
** webservice / download files
- The above workflow should manage the rsync of ws and download files to apiSiteFiles Staging
  - [ ] drive the download file record (see UX channel in slack)

** Unified Relational Database for WDK Application
- Workflow to "union" all organism specific tables from build database(s)
  - use nextflow as this will be run always from start with no "undo".
  - The "deletes" will happen when necessary
- Use sqlloader or postgres bulk loader
- Only load organisms which have changed.
  - use the build database workflowstep name/ date to determine when we need to refresh an organism
- Partition by organism?
  - refresh would first drop the partition for a table instead of trying to delete rows





* Interpro Example
#+name: sqlplus_input 
#+BEGIN_SRC emacs-lisp :var blk="QUERY_NEW_GeneTable" :var sep="\n" :results file :file /home/jbrestel/org_sqlplus.sql :exports none
    (concat "SET AUTOTRACE TRACEONLY;\n"
            "SET TIMING ON;\n"
            "WHENEVER SQLERROR EXIT SQL.SQLCODE;\n"
            "prompt " blk ";\n"
    (save-excursion
      (replace-regexp-in-string "\"" ""
       (mapconcat
        (lambda (x)
          (org-babel-goto-named-src-block x)
          (format "%S" (cadr  (org-babel-get-src-block-info  t))))
        (split-string blk "," t)
        sep)
       t t))
     ";\n"
      "exit\n"
    )
#+END_SRC
#+name: sqlplus
#+BEGIN_SRC sh :noweb yes :results table :var input=sqlplus_input() :exports none
sqlplus jbrestel/$DBI_PASS@uni054n @$input |grep 'QUERY\|Elapsed\|consistent' |perl -e 'while(<>){chomp; if(/consistent gets/) {print $_ . "\n"; }else {print $_ . "\t"} }'
  #+END_SRC

New Tuning Table "InterproResults" in  [[https://github.com/VEuPathDB/ApiCommonModel/blob/master/Model/lib/xml/tuningManager/apiTuningManager.xml][apiTuningnManager.xml]]

** Gene Page Queries

#+CAPTION: Gene Page Queries Summary
| NAME                | Time                 | Gets                |
|---------------------+----------------------+---------------------|
| QUERY_NEW_GeneTable | Elapsed: 00:00:00.02 | 60  consistent gets |
| QUERY_NEW_PBrowse   | Elapsed: 00:00:00.01 | 15  consistent gets |


*** Gene Record Table
#+NAME: QUERY_NEW_GeneTable
#+begin_src sql
SELECT o.*  FROM (SELECT f.* FROM (select
  listagg(ir.transcript_source_id, ', ') within group (order by ir.transcript_source_id) as transcript_ids
, ir.gene_source_id as source_id
, ir.project_id
, ir.interpro_db_name AS interpro_name
, ir.interpro_primary_id
, ir.interpro_secondary_id
, ir.interpro_desc
, ir.interpro_start_min
, ir.interpro_end_min
, ir.interpro_e_value
, ir.interpro_family_id
FROM
  ApidbTuning.interproresults ir
group by ir.project_id, ir.gene_source_id, ir.interpro_db_name, ir.interpro_primary_id, 
         ir.interpro_secondary_id, ir.interpro_desc, ir.interpro_start_min, 
         ir.interpro_end_min, ir.interpro_e_value, ir.gene_source_id, ir.interpro_family_id
order by
transcript_ids
, interpro_name
, interpro_start_min
) f WHERE f.source_id = 'PF3D7_0100100'
) o

#+end_src
#+CALL: sqlplus(input=sqlplus_input("QUERY_NEW_GeneTable")) :exports none

#+RESULTS: sqlplus(input=sqlplus_input("QUERY_NEW_GeneTable"))
| QUERY_NEW_GeneTable | Elapsed: 00:00:00.02 | 60  consistent gets |


*** PBrowse

#+NAME: QUERY_NEW_PBrowse
#+begin_src sql
SELECT ir.interpro_primary_id || '_' || ir.interpro_start_min || '_' || ir.interpro_end_min feature_id, 
       'domain' type, 
       'interpro' source, 
       ir.interpro_primary_id name, 
       ir.interpro_e_value score, 
       null parent_id, 
       ir.interpro_start_min startm, 
       ir.interpro_end_min end, 
       'Note=' || ir.interpro_secondary_id || ' ' || ir.interpro_desc || ';' || 
       'Db=' || ir.interpro_db_name || ';' || 
       'InterproId=' || ir.interpro_family_id || ';' || 
       'Evalue=' || ir.interpro_e_value || ';' || 
       'Pi=' || ir.interpro_primary_id atts
             from apidbtuning.interproresults ir, apidbtuning.proteinattributes pa
             where  pa.aa_sequence_id = 7474585 
             and ir.interpro_end_min > 0
             and ir.interpro_start_min < 100000
             and ir.protein_source_id = pa.source_id
#+end_src
#+CALL: sqlplus(input=sqlplus_input("QUERY_NEW_PBrowse")) :exports none

#+RESULTS: sqlplus(input=sqlplus_input("QUERY_NEW_PBrowse"))
| QUERY_NEW_PBrowse | Elapsed: 00:00:00.01 | 15  consistent gets |


** Search 

#+CAPTION: Search Query Summary
| NAME                            | Time                 | Gets                     | Gets improvement |
|---------------------------------+----------------------+--------------------------+------------------|
| QUERY_GenesByInterproDomain     | Elapsed: 00:00:21.16 | 1015065  consistent gets |                  |
| QUERY_NEW_GenesByInterproDomain | Elapsed: 00:00:00.57 | 10056  consistent gets   |             100x |

*** Original Gene ID Search: [[https://plasmodb.org/plasmo/app/search/transcript/GenesByInterproDomain][GenesByInterproDomain]]  
#+NAME: QUERY_GenesByInterproDomain
#+begin_src sql
  SELECT 22 AS wdk_instance_id
         , rownum AS wdk_row_id
         ,  f.*
    FROM (SELECT o.* , 10 AS wdk_weight
            FROM (SELECT ga.source_id, ga.gene_source_id
                                     , 'Y' as matched_result
                                     , ga.project_id,
                                     to_char(avg(trunc(df.e_value,100)),'9.999EEEE') as e_value,
                                     max(df.e_value) as sorting_value 
                    FROM dots.DomainFeature df, ApidbTuning.TranscriptAttributes ga,
                                     dots.DbRefAaFeature draf, sres.DbRef dr
                   WHERE ga.aa_sequence_id = df.aa_sequence_id
                     AND df.aa_feature_id = draf.aa_feature_id
                     AND draf.db_ref_id = dr.db_ref_id
                     AND dr.external_database_release_id in (24,163,2680)
                     AND (dr.primary_identifier IN('PF03011')
                          OR dr.secondary_identifier IN('PF03011')
                          OR lower(dr.primary_identifier) like lower(REPLACE('N/A', '*', '%'))
                          OR lower(dr.secondary_identifier) like lower(REPLACE('N/A', '*', '%'))
                          OR lower(dr.primary_identifier || ' : ' || dr.secondary_identifier)
                          like lower(REPLACE('N/A', '*', '%'))
                          OR lower(dr.remark) like lower(REPLACE('N/A', '*', '%')))
                     AND ga.taxon_id IN (2320986,2320988,1551685,2321006,2320989,1551696,2321007,
                                         1553638,1553633,1551592,1551586,2320993,1551497,2320996,
                                         2320997,2320994,1551532,2320995,2320998,2320992,2321003,
                                         2321000,2321002,2321001,2320999,2321020,2320991,2320990,
                                         2321019,1553651,2321025,1553660,2321024,2321023,2321021,
                                         2320987,2321004,2321005,2321018,2321014,2321016,2321015,
                                         2321012,2321011,2321013,2321010,2321022,1553646,2321017,
                                         2321008,1551691,2321009,2320964,1547847,2320962,1547852,
                                         2320960,2320961,2320953,1547439,1547447,1547466,1547419,
                                         2321089,1554984,2321086,2321087,2321083,2321080,1554981,
                                         2321088,1554990,2321090,2321081,2320975,2320974,2320968,
                                         2320971,2320970,2320969,2320967,2320972,2320973,1555386,
                                         2320982,2320980,2320981,1556022,2321141,2320978,2320979,
                                         1555669,1555666,1555652,1555664,1555667,1555655,1555659,
                                         1555686,1555676,1555648,1555687,1555660,1555691,1555645,
                                         1555633,2321079,1553628,1551490,1551489,1553658,1551664,
                                         1551698,1553640,1552127,1551687,1547809,1547403,1554983,
                                         1554989,1555490,1555051,1556009,1555698,1555626,1553779)
                   GROUP BY ga.source_id,ga.gene_source_id,ga.project_id
            ) o
    ) f
#+end_src
#+CALL: sqlplus(input=sqlplus_input("QUERY_GenesByInterproDomain")) :exports none
#+RESULTS: sqlplus(input=sqlplus_input("QUERY_GenesByInterproDomain"))
| QUERY_GenesByInterproDomain | Elapsed: 00:00:21.16 | 1015065  consistent gets |

*** New Gene ID Search
#+NAME: QUERY_NEW_GenesByInterproDomain
#+begin_src sql
  SELECT 11 AS wdk_instance_id, rownum AS wdk_row_id,  f.* FROM (SELECT o.* , 10 AS wdk_weight FROM (SELECT ir.transcript_source_id as source_id, ir.gene_source_id, 'Y' as matched_result, ir.project_id,
                     to_char(avg(trunc(ir.interpro_e_value,100)),'9.999EEEE') as e_value,
                     max(ir.interpro_e_value) as sorting_value 
              FROM ApiDBTuning.InterproResults ir
              WHERE ir.interpro_db_name = 'PFAM'
                AND (ir.interpro_primary_id IN('PF03011')
                     OR ir.interpro_secondary_id IN('PF03011')
                     OR lower(ir.interpro_primary_id) like lower(REPLACE('N/A', '*', '%'))
                     OR lower(ir.interpro_secondary_id) like lower(REPLACE('N/A', '*', '%'))
                     OR lower(ir.interpro_primary_id || ' : ' || ir.interpro_secondary_id)
                        like lower(REPLACE('N/A', '*', '%'))
                     OR lower(ir.interpro_desc) like lower(REPLACE('N/A', '*', '%')))
                AND ir.organism IN ('Hepatocystis sp. ex Piliocolobus tephrosceles 2019','Plasmodium adleri G01','Plasmodium berghei ANKA',
  'Plasmodium billcollinsi G01','Plasmodium blacklocki G01','Plasmodium chabaudi chabaudi','Plasmodium coatneyi Hackeri',
  'Plasmodium cynomolgi strain B','Plasmodium cynomolgi strain M','Plasmodium falciparum 3D7','Plasmodium falciparum 7G8',
  'Plasmodium falciparum CD01','Plasmodium falciparum Dd2','Plasmodium falciparum GA01','Plasmodium falciparum GB4',
  'Plasmodium falciparum GN01','Plasmodium falciparum HB3','Plasmodium falciparum IT','Plasmodium falciparum KE01','Plasmodium falciparum KH01',
  'Plasmodium falciparum KH02','Plasmodium falciparum ML01','Plasmodium falciparum SD01','Plasmodium falciparum SN01',
  'Plasmodium falciparum TG01','Plasmodium fragile strain nilgiri','Plasmodium gaboni strain G01','Plasmodium gaboni strain SY75','Plasmodium gallinaceum 8A',
  'Plasmodium inui San Antonio 1','Plasmodium knowlesi strain A1H1','Plasmodium knowlesi strain H','Plasmodium knowlesi strain Malayan Strain Pk1 A',
  'Plasmodium malariae UG01','Plasmodium ovale curtisi GH01','Plasmodium praefalciparum strain G01','Plasmodium reichenowi CDC','Plasmodium reichenowi G01','Plasmodium relictum SGS1-like',
  'Plasmodium vinckei Cameroon EL','Plasmodium vinckei brucechwatti DA','Plasmodium vinckei lentum DE','Plasmodium vinckei petteri CR 2020',
  'Plasmodium vinckei petteri strain CR','Plasmodium vinckei vinckei CY','Plasmodium vinckei vinckei strain vinckei','Plasmodium vivax P01',
  'Plasmodium vivax Sal-1','Plasmodium vivax-like Pvl01','Plasmodium yoelii yoelii 17X','Plasmodium yoelii yoelii 17XNL','Plasmodium yoelii yoelii YM',
  'Babesia bigemina strain BOND','Babesia bovis T2Bo','Babesia divergens strain 1802A','Babesia microti strain RI','Babesia ovata strain Miyake',
  'Babesia sp. Xinjiang Xinjiang','Cytauxzoon felis strain Winnie','Theileria annulata strain Ankara','Theileria equi strain WA',
  'Theileria orientalis strain Shintoku','Theileria parva strain Muguga','Cryptosporidium andersoni isolate 30847','Cryptosporidium hominis TU502',
  'Cryptosporidium hominis UdeA01','Cryptosporidium hominis isolate 30976','Cryptosporidium hominis isolate TU502_2012','Cryptosporidium meleagridis strain UKMEL1',
  'Cryptosporidium muris RN66','Cryptosporidium parvum IOWA-ATCC','Cryptosporidium parvum Iowa II','Cryptosporidium tyzzeri isolate UGA55',
  'Cryptosporidium ubiquitum isolate 39726','Cyclospora cayetanensis isolate NF1_C8','Cyclospora cayetanensis strain CHN_HEN01',
  'Eimeria acervulina Houghton','Eimeria brunetti Houghton','Eimeria falciformis Bayer Haberkorn 1970','Eimeria maxima Weybridge','Eimeria mitis Houghton',
  'Eimeria necatrix Houghton','Eimeria praecox Houghton','Eimeria tenella strain Houghton','Besnoitia besnoiti strain Bb-Ger1','Cystoisospora suis strain Wien I',
  'Hammondia hammondi strain H.H.34','Neospora caninum Liverpool','Neospora caninum Liverpool 2019','Sarcocystis neurona SN3','Sarcocystis neurona SO SN1',
  'Toxoplasma gondii ARI','Toxoplasma gondii CAST','Toxoplasma gondii COUG','Toxoplasma gondii FOU','Toxoplasma gondii GAB2-2007-GAL-DOM2','Toxoplasma gondii GT1','Toxoplasma gondii MAS',
  'Toxoplasma gondii ME49','Toxoplasma gondii RH-88','Toxoplasma gondii RUB','Toxoplasma gondii TgCATBr9','Toxoplasma gondii TgCatPRC2','Toxoplasma gondii VAND','Toxoplasma gondii VEG',
  'Toxoplasma gondii p89','Gregarina niphandrodes Unknown strain','Plasmodium cynomolgi','Plasmodium falciparum','Plasmodium gaboni','Plasmodium knowlesi','Plasmodium reichenowi',
  'Plasmodium vinckei','Plasmodium vivax','Plasmodium vivax-like sp.','Plasmodium yoelii','Babesiidae','Theileria','Cryptosporidium hominis','Cryptosporidium parvum',
  'Cyclospora','Eimeria','Neospora','Sarcocystis','Toxoplasma','Eugregarinorida')
                GROUP BY ir.transcript_source_id,ir.gene_source_id,ir.project_id
  ) o) f
#+end_src
#+CALL: sqlplus(input=sqlplus_input("QUERY_NEW_GenesByInterproDomain")) :exports none
#+RESULTS: sqlplus(input=sqlplus_input("QUERY_NEW_GenesByInterproDomain"))
| QUERY_NEW_GenesByInterproDomain | Elapsed: 00:00:00.57 | 10056  consistent gets |


** Domain Database Param


#+CAPTION: Domain Database Param Query Summary
| NAME                                | Time                 | Gets                      | Gets improvement |
|-------------------------------------+----------------------+---------------------------+------------------|
| QUERY_DomainDatabase                | Elapsed: 00:01:06.40 | 28027001  consistent gets |                  |
| QUERY_NEW_DomainDatabase_PRE_TABLE  | Elapsed: 00:00:02.67 | 334333  consistent gets   | 80x              |
| QUERY_NEW_DomainDatabase_WITH_TABLE | Elapsed: 00:00:00.01 | 19  consistent gets       | 1,475,105x       |

*** Original Domain Database
#+NAME: QUERY_DomainDatabase
#+begin_src sql
  SELECT 7 AS wdk_instance_id,
         rownum AS wdk_row_id,
         f.*
    FROM (SELECT o.*
            FROM (select database as term,
                         listagg(external_database_release_id, ',') within group (order by external_database_release_id) as internal
                    from (SELECT distinct upper(CASE WHEN (upper(ed.name)like 'INTERPRO%') 
                                                     THEN 'INTERPRO'  ELSE ed.name END ) AS database,
                                          edr.external_database_release_id
                            FROM sres.DbRef dr, 
                                 sres.ExternalDatabaseRelease edr,
                                 sres.ExternalDatabase ed
                           WHERE dr.external_database_release_id = edr.external_database_release_id
                             AND edr.external_database_id = ed.external_database_id
                             AND dr.db_ref_id IN (select draf.db_ref_id
                                                    from dots.dbrefaafeature draf
                                                         , dots.domainfeature df
                                                         , sres.externaldatabase d
                                                         , sres.externaldatabaserelease r
                                                   where draf.aa_feature_id = df.aa_feature_id
                                                     and df.external_database_release_id = r.external_database_release_id
                                                     and r.external_database_id = d.external_database_id
                                                     and d.name IN('InterproscanData_RSRC', 'INTERPRO',
                                                                   'Prints', 'HAMAP', 'SFLD', 'TIGRFAM',
                                                                   'SUPERFAMILY', 'Pfam', 'PIRSF',
                                                                   'PROSITE patterns', 'Superfamily', 'PRINTS',
                                                                   'InterProScan', 'PFAM', 'SMART', 'CDD', 'PANTHER')
                             )
                    )
                   group by database
                   order by term
            ) o
    ) f
#+end_src
#+CALL: sqlplus(input=sqlplus_input("QUERY_DomainDatabase")) :exports none
#+RESULTS: sqlplus(input=sqlplus_input("QUERY_DomainDatabase"))
| QUERY_DomainDatabase | Elapsed: 00:01:06.40 | 28027001  consistent gets |

*** New Domain Database
#+NAME: QUERY_NEW_DomainDatabase
#+begin_src sql
SELECT 4 AS wdk_instance_id, rownum AS wdk_row_id,  f.* FROM (SELECT o.*  FROM (select distinct interpro_db_name as internal
                            , case when upper(interpro_db_name) like 'INTERPRO%'
                                   THEN 'INTERPRO'  ELSE interpro_db_name END  AS term
               from apidbtuning.interprodomaindatabase
              order by term
) o) f
#+end_src
#+CALL: sqlplus(input=sqlplus_input("QUERY_NEW_DomainDatabase")) :exports none
#+RESULTS: sqlplus(input=sqlplus_input("QUERY_NEW_DomainDatabase"))
| QUERY_NEW_DomainDatabase | Elapsed: 00:00:00.01 |   | 19  consistent gets |


** Domain Accession Param

#+CAPTION: Domain Accession Param Query Summary
| NAME                                 | Time                 | Gets                     | Gets improvement |
|--------------------------------------+----------------------+--------------------------+------------------|
| QUERY_DomainAccession                | Elapsed: 00:00:30.42 | 4599061  consistent gets |                  |
| QUERY NEW_DomainAccession_PRE_INDEX  | Elapsed: 00:00:01.26 | 667528  consistent gets  |               7x |
| QUERY_NEW_DomainAccession_WITH_INDEX | Elapsed: 00:00:01.57 | 38578  consistent gets   |             120x |
| QUERY_NEW_DomainAccession_WITH_TABLE | Elapsed: 00:00:00.26 | 1189  consistent gets    |            3800x |


*** Original Domain Accession
#+NAME: QUERY_DomainAccession
#+begin_src sql
  SELECT 8 AS wdk_instance_id,
         rownum AS wdk_row_id,
         f.*
    FROM (SELECT o.*
            FROM (select *
                    from (SELECT dr.primary_identifier AS internal,
                                 dr.primary_identifier || ' : ' || dr.secondary_identifier AS term,
                                 dr.primary_identifier || ' : ' || dr.secondary_identifier || ' ' ||
                                   dr.remark AS display,
                                 count(*) as ct_hits
                            from dots.domainfeature df, dots.dbrefaafeature draf,sres.dbref dr,
                                 sres.ExternalDatabaseRelease edr, sres.ExternalDatabase ed
                           where df.aa_feature_id = draf.aa_feature_id
                             and dr.db_ref_id = draf.db_ref_id
                             and dr.external_database_release_id = edr.external_database_release_id
                             AND edr.external_database_id = ed.external_database_id
                             AND edr.external_database_release_id IN (24,163,2680)
                             AND dr.primary_identifier IS NOT NULL
                           group by dr.primary_identifier,dr.secondary_identifier,dr.remark
                           UNION
                          SELECT 'N/A', 'N/A', 'N/A', 0.5 FROM dual)
                   order by ct_hits desc
            ) o
    ) f
#+end_src
#+CALL: sqlplus(input=sqlplus_input("QUERY_DomainAccession")) :exports none
#+RESULTS: sqlplus(input=sqlplus_input("QUERY_DomainAccession"))
| QUERY_DomainAccession | Elapsed: 00:00:30.42 | 4599061  consistent gets |

*** New Domain Accession
#+NAME: QUERY_NEW_DomainAccession
#+begin_src sql
SELECT 8 AS wdk_instance_id, rownum AS wdk_row_id,  f.* FROM (SELECT o.*  FROM (select interpro_primary_id as internal
                   , interpro_primary_id || ' : ' || interpro_secondary_id AS term
                   , interpro_primary_id || ' : ' || interpro_secondary_id || ' ' ||
                     interpro_desc as display
                   , count(*) as ct_hits
              from APIDBTUNING.INTERPRODOMAINACCESSION
              where interpro_db_name = 'PFAM'
              group by interpro_primary_id, interpro_secondary_id, interpro_desc
) o) f
#+end_src
#+CALL: sqlplus(input=sqlplus_input("QUERY_NEW_DomainAccession")) :exports none

#+RESULTS: sqlplus(input=sqlplus_input("QUERY_NEW_DomainAccession"))
| QUERY_NEW_DomainAccession | Elapsed: 00:00:00.26 | 1189  consistent gets |


* Appendix
** JBrowse 
- Example POST to get wdk Table for a gene
  #+begin_example
  curl -X POST -d '{primaryKey: [{name: "source_id", value: "PF3D7_1133400"}, {name: "project_id", value: "PlasmoDB"}], attributes: [], tables: ["GOTerms"]}' -H 'Content-Type: application/json'  https://w2.plasmodb.org/plasmo/service/record-types/gene/records
  #+end_example
- Example Track
  #+begin_example
  [tracks.testGene]
  urlTemplate=PlasmoDB-54_Pfalciparum3D7_sorted.gff.gz
  storeClass=JBrowse/Store/SeqFeature/GFF3Tabix
  type=CanvasFeatures
  category=Gene Models
  key=Annotated Transcripts (UTRs in White when available) TEST
  type=NeatCanvasFeatures/View/Track/NeatFeatures
  glyph=JBrowse/View/FeatureGlyph/Gene
  unsafePopup=true
  onClick.content={geneTestDetails}
  menuTemplate+=json:{"label": "View Details", "content": "{geneTestDetails}"}
  #+end_example
- Example function to create popup from POST
 #+begin_src js
    geneTestDetails = function(track, feature, featureDiv, coreDetails) {
       var c = track.browser.config;
       container = dojo.create('div', {
           className: 'detail feature-detail feature-detail-' + track.name.replace(/\s+/g, '_').toLowerCase(),
                innerHTML: ''
              });
       var coreDetails = dojo.create('div', {
                className: 'core'
              }, container);
       var hitchCore = dojo.hitch(track, 'renderDetailField', coreDetails);
       coreDetails.innerHTML += '<h2 class="sectiontitle">Gene Details</h2>';
       var gene = feature.data.id;
       hitchCore( 'Gene', gene, feature );
       var endDetails = dojo.create('div', {
                 className: 'end'
              }, container);
       var hitchEnd = dojo.hitch(track, 'renderDetailField', endDetails);
       var goRows = new Array();
       // how to get project_id here??
       var data = {primaryKey: [{name: "source_id", value: gene}, {name: "project_id", value: "PlasmoDB"}], attributes: [], tables: ["GOTerms"]};
       c.fetchWithPost("/a/service/record-types/gene/records", data)
         .then(obj => {
                    obj.tables.GOTerms.map(x => goRows.push(c.twoColRow(x.go_id, x.ontology)));
                    hitchEnd('GOTerms', c.goTermTable(goRows), feature);
                 });
       return container;
       }          
  #+end_src


** Table Usage
*** ApiDBTuning
**** ApiDBTuning.AASEQUENCEINFO
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.ANNOTATEDGENOMESUMMARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
**** ApiDBTuning.ANNOTATIONCHANGE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.APOLLOID
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
**** ApiDBTuning.APOLLOUPDATE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.BLASTX
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.CHANGEDGENEPRODUCT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
**** ApiDBTuning.CHIPCHIPTRANSCRIPT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDBTuning.CHRCOPYNUMBERS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDBTuning.CODINGSEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolGeneOrf.pm
**** ApiDBTuning.COMPOUNDATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
**** ApiDBTuning.COMPOUNDID
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
**** ApiDBTuning.DATASETCONTACT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/DataProviderContactEmail.pm
**** ApiDBTuning.DATASETEXAMPLESOURCEID
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** ApiDBTuning.DATASETGENELIST
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebService/WSFPlugin/geneListComparison.pl
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebService/WSFPlugin/fisherExactTest.pl
**** ApiDBTuning.DATASETHISTORY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/eupathBuildRecord.xml
**** ApiDBTuning.DATASETMODELREF
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/datasetQueries.xml
**** ApiDBTuning.DATASETNAMETAXON
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/datasetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/datasetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/View/GraphPackage/Util.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/DataProviderContactEmail.pm
**** ApiDBTuning.DATASETPRESENTER
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/sampleTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/eupathBuildRecord.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/datasetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ElementNamesWithDisplayName.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/DataProviderContactEmail.pm
**** ApiDBTuning.DATASETPROPERTY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/datasetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
**** ApiDBTuning.DATASETPUBLICATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
**** ApiDBTuning.DEFAULTCHARS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.EPITOPESUMMARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml

**** ApiDBTuning.EQTLSPAN
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.ESTALIGNMENTGENESUMMARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/estQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDBTuning.ESTATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/estQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolContigs.pm
**** ApiDBTuning.ESTSEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolContigs.pm
**** ApiDBTuning.EUPATHBUILDDATES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** ApiDBTuning.EXPRESSIONGRAPHSDATA
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.EXTERNALDBDATASETPRESENTER
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/sampleTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml

**** ApiDBTuning.GBROWSETRACKSORGANISM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
**** ApiDBTuning.GENEATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptSummaryQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/spanQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/.organismParams.xml.swp
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/stepAnalysisParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/SenseAntisenseX.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/UDProfileValues.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/SenseAntisenseY.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebService/WSFPlugin/fisherExactTest.pl
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/RNASeq.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/PhenotypeScore.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/Proteomics/NonRatio.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/UniprotDBXRefs.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/KeggPathways.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/Model/AbstractEnrichment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/Model/PathwaysEnrichment.pm
**** ApiDBTuning.GENECOPYNUMBERS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDBTuning.GENEGOTABLE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.GENEGROUPPROFILE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.GENEID
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/spanQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/estQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/UniprotDBXRefs.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolGeneOrf.pm
**** ApiDBTuning.GENEINTJUNCSTATS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.GENEINTRONJUNCTION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.GENEPOPSETOVERLAP
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
**** ApiDBTuning.GENEPUBMED
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.GENEWORD
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/Model/WordEnrichment.pm
**** ApiDBTuning.GENOMICSEQATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicSummaryQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/spanQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/estQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/genomicQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/orfQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/genomicParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/.organismParams.xml.swp
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/multipleSeqAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolContigs.pm
**** ApiDBTuning.GENOMICSEQUENCEID
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/genomicQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolContigs.pm
**** ApiDBTuning.GENOMICSEQUENCESEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/IsolateAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolContigs.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolGeneOrf.pm
**** ApiDBTuning.GOSUBSETLEAF
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.GOTERMSUMMARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/stepAnalysisParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/Model/GoEnrichment.pm
**** ApiDBTuning.INFERREDCHARS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipTableQueries.xml
**** ApiDBTuning.INFERREDPARAMS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.INTERPRODATA
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
**** ApiDBTuning.INTRONUTRCOORDS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.METADATA
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/snpParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/rflpIsolateParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ElementNamesWithMetaData.pm
**** ApiDBTuning.MSMODIFIEDPEPTIDESUMMARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDBTuning.MSPEPTIDESUMMARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDBTuning.ONTOLOGY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/rflpIsolateParams.xml
**** ApiDBTuning.ORGANISMABBREVIATIONBLAST
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
**** ApiDBTuning.ORGANISMABBREVIATIONWS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/similarityParams.xml
**** ApiDBTuning.ORGANISMATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/orfAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/organismQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/datasetParams.xml
**** ApiDBTuning.ORGANISMSELECTTAXONRANK
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.ORGANISMTREE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/similarityParams.xml
**** ApiDBTuning.ORTHOLOGOUSGENES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebService/WSFPlugin/geneListComparison.pl
**** ApiDBTuning.PANIO
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDBTuning.PANRESULTS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/sampleTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/View/GraphPackage/Util.pm
**** ApiDBTuning.PATHWAYATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/pathwayParams.xml
**** ApiDBTuning.PATHWAYCOMPOUNDS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/Model/PathwaysEnrichment.pm
**** ApiDBTuning.PATHWAYEDGES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayTableQueries.xml
**** ApiDBTuning.PATHWAYNODES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayTableQueries.xml
**** ApiDBTuning.PATHWAYREACTIONS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/Model/PathwaysEnrichment.pm
**** ApiDBTuning.PATHWAYSGENETABLE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.PDBSIMILARITY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** ApiDBTuning.POPSETATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolContigs.pm
**** ApiDBTuning.POPSETSEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/IsolateAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolContigs.pm
**** ApiDBTuning.PROFILE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/View/GraphPackage/Util.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ProfileByEC.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/Profile.pm
**** ApiDBTuning.PROFILESAMPLES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/SenseAntisenseX.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/SenseAntisenseY.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ElementNamesWithMetaData.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ElementNamesWithDisplayName.pm
**** ApiDBTuning.PROFILESETDISPLAYINFO
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.PROFILETYPE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/metabolomics.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/View/GraphPackage/Util.pm
**** ApiDBTuning.PROPERTYTYPE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.PROTEINATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
**** ApiDBTuning.PROTEINSEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/STRING.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/Mitoprot.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/ChloroP.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/IsolateAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/InterPro.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/NcbiBLAST.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/MendelGPI.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/WolfPSORT.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolGeneOrf.pm
**** ApiDBTuning.RFLPGENOTYPES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/rflpIsolateAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/rflpIsolateQueries.xml
**** ApiDBTuning.RNASEQSTATS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDBTuning.SAMPLEDISPLAYINFO
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDBTuning.SAMPLEPROCESS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/rflpIsolateAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/sampleTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/rflpIsolateQueries.xml
**** ApiDBTuning.SAMPLES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/rflpIsolateAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/rflpIsolateQueries.xml
**** ApiDBTuning.SEQUENCEPIECECLOSURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
**** ApiDBTuning.SIMILARITYSPANLOCATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.SNPATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/snpQueries.xml
**** ApiDBTuning.SNPATTRIBUTESDOTS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/snpChipQueries.xml
**** ApiDBTuning.SNPCHIPATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/snpChipQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/snpChipParams.xml
**** ApiDBTuning.SNPCHIPSTRAINS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** ApiDBTuning.SNPSTRAINS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** ApiDBTuning.SPLICESITETRANSCRIPTS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDBTuning.STRINGDB
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.SUBCELLULAR
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDBTuning.TAXONOMY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
**** ApiDBTuning.TAXONSPECIES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** ApiDBTuning.TFBSGENE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDBTuning.TRANSCRIPTATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptSummaryQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/recordParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/.organismParams.xml.swp
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/similarityParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ProfileByEC.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/multipleSeqAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/IsolateAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolGeneOrf.pm
**** ApiDBTuning.TRANSCRIPTCENDISTANCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/.organismParams.xml.swp
**** ApiDBTuning.TRANSCRIPTPATHWAY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/pathwayParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/Model/PathwaysEnrichment.pm
**** ApiDBTuning.TRANSCRIPTSEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/IsolateAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolGeneOrf.pm
*** ApiDB
**** ApiDB.AGPPIECE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
**** ApiDB.BLATPROTEINALIGNMENT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDB.CHRCOPYNUMBER
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/genomicQueries.xml
**** ApiDB.COMPOUNDMASSSPECRESULT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
**** ApiDB.COMPOUNDPEAKS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
**** ApiDB.COMPOUNDPEAKSCHEBI
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
**** ApiDB.CRISPRPHENOTYPE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/PhenotypeScore.pm
**** ApiDB.DATASOURCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/.organismParams.xml.swp
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonModel/Model/DataSourceList.pm
**** ApiDB.EXTERNALRESOURCEURL
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDB.FEATURELOCATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/orfTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/orfQueries.xml
**** ApiDB.GENEFEATUREPRODUCT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDB.GENEINTERACTION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.GFF3
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDB.LOPITRESULTS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDB.MASSSPECSUMMARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** ApiDB.NAFEATUREHAPLOBLOCK
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/spanQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.NAFEATUREIMAGE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/GeneImage.pm
**** ApiDB.NAFEATUREMETACYCLE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.NAFEATUREPHENOTYPE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDB.NAFEATUREPHENOTYPEMODEL
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDB.OLDANNOTATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.OLDCODINGSEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDB.ONTOLOGYTERMRESULT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDB.ORGANISM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/templates/RnaSeqGbrowseTemplates.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/multipleSeqAlignment.pm
**** ApiDB.PATHWAYREACTIONXREF
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayTableQueries.xml
**** ApiDB.PHENOTYPEGROWTHRATE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/PhenotypeScore.pm
**** ApiDB.PHENOTYPEMODEL
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDB.PHENOTYPEMUTANTS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.PHENOTYPERESULT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDB.PHENOTYPESCORE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/PhenotypeScore.pm
**** ApiDB.PHYLOGENETICPROFILE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.PUBCHEMSUBSTANCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
**** ApiDB.RFLPGENOTYPE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/rflpIsolateTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/rflpIsolateParams.xml
**** ApiDB.SEQEDIT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDB.SEQUENCEVARIATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipTableQueries.xml
**** ApiDB.SPLICESITEFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.SPLICESITEGENES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.SYNTENICGENE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDB.SYNTENY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
**** ApiDB.TRANSCRIPTLOCATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDB.TRANSCRIPTPRODUCT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
*** chEBI
**** chEBI.CHEMICAL_DATA
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
**** chEBI.COMPOUNDS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
**** chEBI.DEFAULT_STRUCTURES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundAttributeQueries.xml
**** chEBI.NAMES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundAttributeQueries.xml
**** chEBI.STRUCTURES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundAttributeQueries.xml
*** Core
**** Core.ALGORITHM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetPresenters/ToxoDB.xml
**** Core.ALGORITHMINVOCATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/sql/installReflowSchema.sql
**** Core.TABLEINFO
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml

  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
*** DoTS
**** DoTS.AAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
    - [ ] Uniprot
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] gene_dbrefs
    - [ ] 3dpreds
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] GenesWithStructurePrediction
**** DoTS.AALOCATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [ ] LowComplexity
    - [ ] SignalP
    - [ ] exportpred
    - [ ] TMHMM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] UnifiedMassSpec 
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] TMHMM
    - [ ] signalp
    - [ ] lowcomplexity
**** DoTS.AASEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [ ] LowComplexity
    - [ ] exportpred
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] UnifiedMassSpec     
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] LowComplexity    
**** DoTS.AASEQUENCEENZYMECLASS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
    - [ ] pathway plot
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] ECNumbers
    - [ ] ECNumbersInferred      
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] GenesByECNumber
    - [ ] GenesByECNumberDirect
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
    - [ ] ECNumberList
    - [ ] ECNumberSource
    - [ ] ECNumberAllSources
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/PathwayGeneraData.pm
    - [ ] pathway plot
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ProfileByEC.pm
    - [ ] pathway plot
**** DoTS.AASEQVARIATION                                   :SteveF:DELETE:
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/WDK/Model/GDUtil/Transducer/GUSAASequenceTransducer.pm
    - [ ] DELETE
**** DoTS.BINDINGSITEFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] Binding Site Feature
**** DoTS.BLATALIGNMENT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] piggyBac transposable elements
    - [ ] generic end feature
    - [ ] dbest
    - [ ] old gene models ???
    - [ ] alignment:sequences (maxicircle, ...)
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estTableQueries.xml
    - [ ] EST Alignment
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanTableQueries.xml
    - [ ] ESTs
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/estQueries.xml
    - [ ] ESTs by location
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
    - [ ] withchrom est
**** DoTS.CHROMOSOMEELEMENTFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] haplotype block feature (eqtl)
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/spanQueries.xml
    - [ ] eqtl segments
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] eqtl segments    
**** DoTS.DBREFAAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
    - [ ] Uniprot
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] gene_dbrefs
    - [ ] 3dpreds
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] Reagents
    - [ ] StructurePrediction
**** DoTS.DBREFNAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] Metabolic Pathways
    - [ ] Antibody
    - [ ] gene_dbrefs
    - [ ] FungiOrgLinkouts
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
    - [ ] where reviewed??  what is this?
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] MetabolicPathways Haggai
    - [ ] Reagents (Crypto??) 
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
    - [ ] Metabolic Pathways
**** DoTS.DBREFNASEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
    - [ ] db refs
**** DoTS.DOMAINFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [X] Interpro
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [X] Interpro
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [X] Interpro
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
    - [X] Interpro
**** DoTS.EPITOPEFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] GenesWithEpitopes
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/WDK/Model/GDUtil/Transducer/GUSAASequenceTransducer.pm
    - [ ] probably unused??
**** DoTS.EST
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
    - [ ] ESTs
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] ESTs    
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estAttributeQueries.xml
    - [ ] ESTs    
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estTableQueries.xml
    - [ ] ESTs    
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanTableQueries.xml
    - [ ] ESTs    
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
    - [ ] ESTs    

**** DoTS.EXTERNALNASEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/spanQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/genomicQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** DoTS.GENEFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] repeat region
    - [ ] alternate gene models
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] Preferred Products
    - [ ] GeneId
    - [ ] ProteinDatabase
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
    - [ ] gene overlap
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
    - [ ] withGff genes
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/WDK/Model/GDUtil/Transducer/ExpressionGraph.pm
    - [ ] Steve
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/GeneImage.pm
    - [ ] Gene Image (Cellular location??)
**** DoTS.GOASSOCINSTEVIDCODE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] PreferredProducts
    - [ ] AlternativeProducts
**** DoTS.ISOLATEFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
**** DoTS.ISOLATESOURCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
**** DoTS.LIBRARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] dbest
**** DoTS.LOWCOMPLEXITYAAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [ ] Low Complexity
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] Low Complexity    
**** DoTS.LOWCOMPLEXITYNAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] Low Complexity    
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
    - [ ] Low Complexity        
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/WDK/Model/GDUtil/Transducer/GUSGenomicContextTransducer.pm
    - [ ] Steve
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/WDK/Model/GDUtil/Transducer/GUSGenomicSeqTransducer.pm
    - [ ] Steve    
**** DoTS.MASSSPECFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] Mass Spec
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
    - [ ] ms_assay
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/WDK/Model/GDUtil/Transducer/GUSAASequenceTransducer.pm
    - [ ] Steve    
**** DoTS.MOTIFAASEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] GenesWithEpitopes
**** DoTS.NAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] Various Queries (ok if we dump these as files)
**** DoTS.NAFEATURECOMMENT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] Notes
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
    - [ ] Repeats
**** DoTS.NALOCATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] Various Queries (ok if we dump these as files)
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/spanQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** DoTS.NASEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/genomicQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/HtsSNPAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/IsolateAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/MultipleAlignmentMercatorMavid.pm
**** DoTS.NASEQUENCEREF
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
**** DoTS.REPEATS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** DoTS.RNAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] trnas
**** DoTS.RNAFEATUREEXON
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] gene models
**** DoTS.SCAFFOLDGAPFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/WDK/Model/GDUtil/Transducer/GUSGenomicSeqTransducer.pm
    - [ ] Steve    
**** DoTS.SECONDARYSTRUCTURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** DoTS.SECONDARYSTRUCTURECALL
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** DoTS.SIGNALPEPTIDEFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** DoTS.SIMILARITY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] popset
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
    - [ ] popset
**** DoTS.SNPFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
    - [ ] barcode snps
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/snpChipQueries.xml
**** DoTS.SPLICEDNASEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] Sequences table
**** DoTS.STS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] Microsatellite
**** DoTS.TANDEMREPEATFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
**** DoTS.TRANSCRIPT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [ ] get_feature_by_name (i dont' think this is used anymore???)
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
    - [ ] test count query
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] TMHMM
    - [ ] LowComplexity
    - [ ] PreferredProducts
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] GiardiaGenesByDifferentialExpression (unused???)
**** DoTS.TRANSLATEDAAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [ ] get_feature_by_name (i dont' think this is used anymore???)
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] TMHMM
    - [ ] LowComplexity
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] Reagents
**** DoTS.TRANSLATEDAASEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [ ] get_feature_by_name (i dont' think this is used anymore???)
    - [ ] get_sequence (i dont' think this is used anymore???)      
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] TMHMM
**** DoTS.TRANSMEMBRANEAAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [ ] TMHMM    
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] TMHMM    
**** DoTS.TRANSPOSABLEELEMENT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
*** EDA
**** EDA.ATTRIBUTE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** EDA.ENTITYATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** EDA.ENTITYTYPE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** EDA.ENTITYTYPEGRAPH
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** EDA.STUDY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
*** hmdb
**** hmdb.COMPOUNDS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
*** Platform
**** Platform.REPORTER
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** Platform.REPORTERLOCATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
*** Results
**** Results.COMPOUNDMASSSPEC
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
**** Results.NAFEATUREDIFFRESULT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
**** Results.NAFEATUREEXPRESSION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/SenseAntisenseX.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/SenseAntisenseY.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/RNASeq.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/Proteomics/NonRatio.pm
**** Results.NAFEATUREHOSTRESPONSE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** Results.REPORTERINTENSITY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** Results.SEGMENTRESULT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** Results.SEQVARIATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipTableQueries.xml
*** SRes
**** SRes.BIBLIOGRAPHICREFERENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
**** SRes.CONTACT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estAttributeQueries.xml
**** SRes.DBREF
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** SRes.ENZYMECLASS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/PathwayGeneraData.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ProfileByEC.pm
**** SRes.EXTERNALDATABASE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml

  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml

  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/pathwayParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/rnaSeqTemplates.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/spliceSitesTemplates.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
**** SRes.EXTERNALDATABASERELEASE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml

  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml

  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/pathwayParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/rnaSeqTemplates.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/spliceSitesTemplates.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
**** SRes.GENETICCODE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
**** SRes.ONTOLOGYRELATIONSHIP
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
**** SRes.ONTOLOGYSYNONYM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** SRes.ONTOLOGYTERM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicSummaryQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/.organismParams.xml.swp
**** SRes.PATHWAY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
**** SRes.TAXON
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/genomicQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** SRes.TAXONNAME
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/datasetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/.organismParams.xml.swp
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonModel/Model/DataSourceList.pm
*** Study
**** Study.CHARACTERISTIC
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** Study.OUTPUT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** Study.PROTOCOLAPPNODE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/genomicQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/RNASeq.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/Proteomics/NonRatio.pm
**** Study.PROTOCOLAPPPARAM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** Study.PROTOCOLPARAM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** Study.STUDY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/sampleTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/compoundParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/rnaSeqTemplates.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/RNASeq.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/Proteomics/NonRatio.pm
**** Study.STUDYBIBREF
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
**** Study.STUDYLINK
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/sampleTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/View/GraphPackage/Util.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/RNASeq.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/Proteomics/NonRatio.pm
    
