#+STARTUP: indent
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+TITLE:     Website Performance and Application Specific Databases
#+AUTHOR:    John,Cristina,Steve
#+DESCRIPTION: How to solve performance issues with Genomics websites by building Application Specific Databases
#+OPTIONS:   H:5 num:nil toc:3 p:t tags:not-in-toc
* Website Performance

[[https://drive.google.com/drive/u/2/folders/1IEnXB5j2Emw46-dGyZRs3P-wIZNSVEON][Performance Testing revealed]] general poor performance of the unified database.  In addition, there were several very poor performing tools.  Each area of concern is listed below and proposed solutions if needed.  The general strategy for fixing the website performance will be:
1. Focus initially on worst performers.
2. Use holistic approach to performance tuning.  (tuning for a data type not a specific tool)
3. Duplicate data as needed to speed up applications
   - Eliminate big complicated queries in the application.  Create more de normalized tables
   - nosql database where appropriate (site search, record pages?)
   - flat file stores for genome browsers

     
  | *Area of Concern*             | *Target*      | *TODOs*             | *Cost*                                | *Who*          |
  |-------------------------------+---------------+---------------------+---------------------------------------+----------------|
  | REST Search Result / ID Query | < 1.5 seconds | query tuning        | 2-3 Release cycles (all query tuning) | DD (JI,JB,MH?) |
  | Search Page Load              | < 5 seconds   | query tuning        |                                       | DD (JI,JB,MH?) |
  | Record Table                  | < 1 second    | query tuning        |                                       | DD (JI,JB,MH?) |
  | Record Initial Page Load      | < 5 seconds   | query tuning        |                                       | DD (JI,JB,MH?) |
  | Results Page Completion       | < 1.5 seconds | general wdk         | TODO Steve                            | Infra          |
  | Join To Attributes / Columns  | = component   | general wdk         | TODO Steve                            | Infra          |
  | Download Results              | TBD           | general wdk         | TODO Steve                            | Infra          |
  | Analysis Tools                | TBD           | ??                  | ??                                    | DD             |
  | Record Full Page Load         | TBD           | nosql??             | ??                                    | ??             |
  | Browser Initial Page Load     | < 5 seconds   | jbrowse files       | 2 Release cycles (all jbrowse)        | DD (JB)        |
  | Browser Track                 | < 1 second    | jbrowse files       |                                       | DD (JB)        |
  | Browser iframe                | < 5 seconds   | jbrowse files       |                                       | DD (JB)        |
  | MapVEu                        | same as EDA   | load as EDA studies | 1-2 Release cycles (eda dev/loading)  | DD (JB,JH)     |
  | SRT                           | TBD           | ??                  | ??                                    | ??             |
  | MultiBLAST                    | TBD           | ??                  | ??                                    | Infra          |
  | Site Search                   | < 1.5 seconds | DONE                | NONE                                  |                |
  | Home Page                     | < 5 seconds   | DONE                | NONE                                  |                |
  
** WDK Searches
*** REST Search Result  / ID Query
- GOAL :: as good as portal/or plasmo and < 1.5 seconds

- SOLUTION :: Use holistic approach to create new denormalized tables or add indexes to existing tables.  This will allow us to replace big queries which have many joins.  Each search will be evaluated and fixed as required.  Search id query, param queries, record table and possibly pbrowse track data should be gotten with smallest table joins (one table properly indexed if possible)
  - current model uses lots of tables from normalized schemas
    | *Schema*    | *Notes*                                                     |
    |-------------+-------------------------------------------------------------|
    | ApiDBTuning | remove fk to other schemas                                  |
    | ApidB       | can we retain these or do we need to move to tuning tables? |
    | DoTS        | Do not use in the website application                       |
    | Sres        | Do not use in the website application                       |
    | Core        | Do not use in the website application                       |
    | chebi       | ok                                                          |
    | hmdb        | ok                                                          |
    | platform    | can we retain these or do we need to copy to tuning tables? |
    | Results     | can we retain these or do we need to copy to tuning tables? |
    | Study       | replace with EDA                                            |

- COST :: few days per datatype (example interpro tuningtable,search,params,pbrowse,wdkTable took 3 days 1 fte)
  
*** Results Page Completion
- GOAL :: as good as portal/or plasmo and < 1.5 seconds
- SOLUTION :: There are [[https://docs.google.com/spreadsheets/d/1JF7MZ8cXjua9h0mMRNb3TkfuXjczI0Pl64yXqOJDXOo/edit#gid=2056082386][several queries]] which are run to make search results.  gene results are made worse because we insert transcripts which don't match the result.  Some possible solutions here are:
  1. General wdk performance improvements including column filters.
     - Filter perforamnce depends on result size.
     - the biggy:  doing the group by, to transfer a distribution, not all raw data
     - getting rid of slow single-gene filter
     - using a dedicated, skinny, attribute table to get the organism
  2. Preview results instead directly going to results page

- COST :: TODO Steve


*** Join To Attributes / Columns
- GOAL :: as good as portal/or plasmo

- SOLUTION :: On beta.veupathdb.org there are two issues we need to address:
  1. 10K columns (bad response time and bad ux)
     - this can be greatly ameliorated by dave's idea of filtering them based on the organisms in the result.  would require some wiring
  2. the cost of joining large results to large attribute queries
     - Need to demonstrate this as a problem

- COST :: TODO Steve

*** Download Results
- GOAL :: TBD

- SOLUTION :: Download seems like an area we have some flexibility if the user was made to understand this was a long running process (like multiblast).  Nothing to be done in the short term but long term could consider queue system like multiblast.  

- COST :: TODO Steve

- NOTE :: For the Download Page Form ... The large number of columns is an issue here too.  10K columns most from trasncriptomics datasets.  Same solution as above can be applied here.  Trim by organisms in result set

*** Search Page Load (Parameters)
- GOAL :: Vocab queries are cached;  All params on a search page should load < 5 seconds on initial run.

- SOLUTION :: Same as ID Searches above.  Use holistic approach to create new denormalized tables or add indexes to existing tables.  This will allow us to replace big queries which have many joins.  Each search will be evaluated and fixed as required.

- COST :: few days per datatype (example interpro tuningtable,search,params,pbrowse,wdkTable took 3 days 1 fte)

*** TODO Analysis Tools (example: GO Enrichment)
** WDK Records
*** Individual Tables
 - GOAL :: as good as plasmo ( < 1 seconds)

- SOLUTION :: Same as ID Searches above.  Use holistic approach to create new denormalized tables or add indexes to existing tables.  This will allow us to replace big queries which have many joins.  Each search will be evaluated and fixed as required.

- COST :: few days per datatype (example interpro tuningtable,search,params,pbrowse,wdkTable took 3 days 1 fte)

*** Initial Page Load
- GOAL :: as good as plasmo ( < 5 seconds)

- SOLUTION :: Some improvements have already been made here for the GeneRecord page.  We are likely under 5 seconds for initial page load assuming only record overview is open.  We identified some record interal tables which were poor performing and fixed including (FungiDB specific Linkouts in the overview section).  We also need to evaluate examples from all record types to ensure we are < 5 seconds for each.

*** Full Page Load
- GOAL :: TBD

- SOLUTION :: In the future we could explore caching all record tables/attributes in a nosql database.  JBrowse and DataPlotter graphs would still be loaded as they are now but tables and attributes would be loaded very quickly.

** Genome and Protein Browsers
*** Initial Page Load
- GOAL :: < 5 seconds

- SOLUTION :: There are 2 areas we can explore:
  1. We currently use webservice calls to create configuration of jbrwose tracks per organism.
     - We currently cache only some of these but we can explore caching all of them
  2. For organisms with a lot of functional data (RNASeq) those configurations are large and take a long time (5-7 seconds) to load
     - Need to explore if this is related to #1 or if the files can be made smaller

- COST :: If the size of the config file is truly probelmatic... would need to explore some sort of lazy loading mechanism which is costly as it would be a jbrowse appliation feature.

*** Individual Tracks
- GOAL :: < 1 seconds

- SOLUTION :: JBrowse is meant to be use files as data stores.  We currently use a REST store which queries the GUS Database for many of the tracks.  We can update the ReFlow workflow to dump gff files for all tracks which currently use the REST Store.  Popups can use web service calls (wdk record tables and attributes).

- COST :: There are 30 Genome Queries and ~ 10 PBrowse Queries which we need to update (few weeks effort).  The data loaders would need to create the files in webservices.  The Synteny Track and Intron Junctions are problematic.  For junctions, we need to move data out of tuning manager and into the workflow (high cost; ask Brian).  For Synteny we need to write a custom endpoint which would do the scaling for the visible region.  that is currently being done in sql. Lastly, we would need to change the way we search for genes within jbrowse application.  Currently this is done with another REST service but we'd need to do this from files.

- NOTE :: Even thought this is a big cost, there are some other advantages to doing this:  
  - it would simplify Apollo
  - allow us to run one JBrowse instead of one per site
  - could run JBrowse2 from the same files

*** Gene Page Context (iframes)

- GOAL :: iframes load the entire application so the initial load will not be faster than time to load jbrowse

- SOLUTION :: We already limit the configurations per section.  Ideally each section would only know about the tracks we display in that section but for some sections we are loading more than needed.

- COST :: Refactoring JBRowse configurations per organism could be done as part of the ReFlow steps above.
** MapVEu Application
This will be an EDA Application.  Those tables have been optimized for study data.  We may need to address special issues as they arise
** TODO Sequence Retrieval Tool
** TODO MultiBLAST
** DONE Site Search
- GOAL :: as good as portal/plasmo ( < 1.5 seconds)
** DONE Home Page
- GOAL :: as good as portal/plasmo ( < 5 slower)

* Data Loading
The Goal is to Shorten the Loading time
** Reflow workflow
- use the tuning manager (or other mechanism) to create organism specific tables as the last step in the organism workflow
  - The tuning manager is already able to make organism specific tables
    #+begin_src example
    apidbtuning.pfal3d7_interprodomains1234
    #+end_src
- This step should be fairly stable.  Should only be rerun when organism is undone/ reloaded or global data like GO terms/taxonomy refreshed
- The resulting tuning tables should be self contained
  - [ ] remove any GUS ids (fks to non apidbtuning tables)
- The Build databases can be any number of organisms.  One organism to all organisms
  - component dbs currently control pairwise syntenic alignments
- On this model it doesn't matter how many organisms are loaded into each build instance.  However, the data load team has been hitting issues with Undo
- can we partition by Row_Alg_invocation_id ? (after postgres migration)
  - The Undo mechanism we have in place could drop the partition instead of deleting the rows.
** Tuning Manager
- still need a tuning job for dataset presenters and other global dbs
- tuning job (post reflow) would continue to be quick/dirty way to add features until full reflow wf can be run
** webservice / download files
- The above workflow should manage the rsync of ws and download files to apiSiteFiles Staging
  - [ ] drive the download file record (see UX channel in slack)

** Unified Relational Database for WDK Application
- Workflow to "union" all organism specific tables from build database(s)
  - use nextflow as this will be run always from start with no "undo".
  - The "deletes" will happen when necessary
- Use sqlloader or postgres bulk loader
- Only load organisms which have changed.
  - use the build database workflowstep name/ date to determine when we need to refresh an organism
- Partition by organism?
  - refresh would first drop the partition for a table instead of trying to delete rows





* Appendix
** JBrowse 
- Example POST to get wdk Table for a gene
  #+begin_example
  curl -X POST -d '{primaryKey: [{name: "source_id", value: "PF3D7_1133400"}, {name: "project_id", value: "PlasmoDB"}], attributes: [], tables: ["GOTerms"]}' -H 'Content-Type: application/json'  https://w2.plasmodb.org/plasmo/service/record-types/gene/records
  #+end_example
- Example Track
  #+begin_example
  [tracks.testGene]
  urlTemplate=PlasmoDB-54_Pfalciparum3D7_sorted.gff.gz
  storeClass=JBrowse/Store/SeqFeature/GFF3Tabix
  type=CanvasFeatures
  category=Gene Models
  key=Annotated Transcripts (UTRs in White when available) TEST
  type=NeatCanvasFeatures/View/Track/NeatFeatures
  glyph=JBrowse/View/FeatureGlyph/Gene
  unsafePopup=true
  onClick.content={geneTestDetails}
  menuTemplate+=json:{"label": "View Details", "content": "{geneTestDetails}"}
  #+end_example
- Example function to create popup from POST
 #+begin_src js
    geneTestDetails = function(track, feature, featureDiv, coreDetails) {
       var c = track.browser.config;
       container = dojo.create('div', {
           className: 'detail feature-detail feature-detail-' + track.name.replace(/\s+/g, '_').toLowerCase(),
                innerHTML: ''
              });
       var coreDetails = dojo.create('div', {
                className: 'core'
              }, container);
       var hitchCore = dojo.hitch(track, 'renderDetailField', coreDetails);
       coreDetails.innerHTML += '<h2 class="sectiontitle">Gene Details</h2>';
       var gene = feature.data.id;
       hitchCore( 'Gene', gene, feature );
       var endDetails = dojo.create('div', {
                 className: 'end'
              }, container);
       var hitchEnd = dojo.hitch(track, 'renderDetailField', endDetails);
       var goRows = new Array();
       // how to get project_id here??
       var data = {primaryKey: [{name: "source_id", value: gene}, {name: "project_id", value: "PlasmoDB"}], attributes: [], tables: ["GOTerms"]};
       c.fetchWithPost("/a/service/record-types/gene/records", data)
         .then(obj => {
                    obj.tables.GOTerms.map(x => goRows.push(c.twoColRow(x.go_id, x.ontology)));
                    hitchEnd('GOTerms', c.goTermTable(goRows), feature);
                 });
       return container;
       }          
  #+end_src


** Table Usage
*** ApiDBTuning
**** ApiDBTuning.AASEQUENCEINFO
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.ANNOTATEDGENOMESUMMARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
**** ApiDBTuning.ANNOTATIONCHANGE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.APOLLOID
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
**** ApiDBTuning.APOLLOUPDATE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.BLASTX
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.CHANGEDGENEPRODUCT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
**** ApiDBTuning.CHIPCHIPTRANSCRIPT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDBTuning.CHRCOPYNUMBERS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDBTuning.CODINGSEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolGeneOrf.pm
**** ApiDBTuning.COMPOUNDATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
**** ApiDBTuning.COMPOUNDID
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
**** ApiDBTuning.DATASETCONTACT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/DataProviderContactEmail.pm
**** ApiDBTuning.DATASETEXAMPLESOURCEID
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** ApiDBTuning.DATASETGENELIST
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebService/WSFPlugin/geneListComparison.pl
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebService/WSFPlugin/fisherExactTest.pl
**** ApiDBTuning.DATASETHISTORY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/eupathBuildRecord.xml
**** ApiDBTuning.DATASETMODELREF
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/datasetQueries.xml
**** ApiDBTuning.DATASETNAMETAXON
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/datasetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/datasetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/View/GraphPackage/Util.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/DataProviderContactEmail.pm
**** ApiDBTuning.DATASETPRESENTER
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/sampleTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/eupathBuildRecord.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/datasetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ElementNamesWithDisplayName.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/DataProviderContactEmail.pm
**** ApiDBTuning.DATASETPROPERTY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/datasetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
**** ApiDBTuning.DATASETPUBLICATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
**** ApiDBTuning.DEFAULTCHARS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.EPITOPESUMMARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml

**** ApiDBTuning.EQTLSPAN
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.ESTALIGNMENTGENESUMMARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/estQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDBTuning.ESTATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/estQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolContigs.pm
**** ApiDBTuning.ESTSEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolContigs.pm
**** ApiDBTuning.EUPATHBUILDDATES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** ApiDBTuning.EXPRESSIONGRAPHSDATA
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.EXTERNALDBDATASETPRESENTER
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/sampleTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml

**** ApiDBTuning.GBROWSETRACKSORGANISM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
**** ApiDBTuning.GENEATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptSummaryQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/spanQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/.organismParams.xml.swp
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/stepAnalysisParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/SenseAntisenseX.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/UDProfileValues.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/SenseAntisenseY.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebService/WSFPlugin/fisherExactTest.pl
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/RNASeq.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/PhenotypeScore.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/Proteomics/NonRatio.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/UniprotDBXRefs.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/KeggPathways.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/Model/AbstractEnrichment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/Model/PathwaysEnrichment.pm
**** ApiDBTuning.GENECOPYNUMBERS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDBTuning.GENEGOTABLE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.GENEGROUPPROFILE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.GENEID
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/spanQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/estQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/UniprotDBXRefs.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolGeneOrf.pm
**** ApiDBTuning.GENEINTJUNCSTATS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.GENEINTRONJUNCTION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.GENEPOPSETOVERLAP
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
**** ApiDBTuning.GENEPUBMED
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.GENEWORD
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/Model/WordEnrichment.pm
**** ApiDBTuning.GENOMICSEQATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicSummaryQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/spanQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/estQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/genomicQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/orfQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/genomicParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/.organismParams.xml.swp
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/multipleSeqAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolContigs.pm
**** ApiDBTuning.GENOMICSEQUENCEID
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/genomicQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolContigs.pm
**** ApiDBTuning.GENOMICSEQUENCESEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/IsolateAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolContigs.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolGeneOrf.pm
**** ApiDBTuning.GOSUBSETLEAF
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.GOTERMSUMMARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/stepAnalysisParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/Model/GoEnrichment.pm
**** ApiDBTuning.INFERREDCHARS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipTableQueries.xml
**** ApiDBTuning.INFERREDPARAMS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.INTERPRODATA
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
**** ApiDBTuning.INTRONUTRCOORDS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.METADATA
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/snpParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/rflpIsolateParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ElementNamesWithMetaData.pm
**** ApiDBTuning.MSMODIFIEDPEPTIDESUMMARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDBTuning.MSPEPTIDESUMMARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDBTuning.ONTOLOGY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/rflpIsolateParams.xml
**** ApiDBTuning.ORGANISMABBREVIATIONBLAST
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
**** ApiDBTuning.ORGANISMABBREVIATIONWS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/similarityParams.xml
**** ApiDBTuning.ORGANISMATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/orfAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/organismQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/datasetParams.xml
**** ApiDBTuning.ORGANISMSELECTTAXONRANK
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.ORGANISMTREE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/similarityParams.xml
**** ApiDBTuning.ORTHOLOGOUSGENES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebService/WSFPlugin/geneListComparison.pl
**** ApiDBTuning.PANIO
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDBTuning.PANRESULTS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/sampleTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/View/GraphPackage/Util.pm
**** ApiDBTuning.PATHWAYATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/pathwayParams.xml
**** ApiDBTuning.PATHWAYCOMPOUNDS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/Model/PathwaysEnrichment.pm
**** ApiDBTuning.PATHWAYEDGES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayTableQueries.xml
**** ApiDBTuning.PATHWAYNODES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayTableQueries.xml
**** ApiDBTuning.PATHWAYREACTIONS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/Model/PathwaysEnrichment.pm
**** ApiDBTuning.PATHWAYSGENETABLE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.PDBSIMILARITY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** ApiDBTuning.POPSETATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolContigs.pm
**** ApiDBTuning.POPSETSEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/IsolateAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolContigs.pm
**** ApiDBTuning.PROFILE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/View/GraphPackage/Util.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ProfileByEC.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/Profile.pm
**** ApiDBTuning.PROFILESAMPLES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/SenseAntisenseX.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/SenseAntisenseY.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ElementNamesWithMetaData.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ElementNamesWithDisplayName.pm
**** ApiDBTuning.PROFILESETDISPLAYINFO
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.PROFILETYPE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/metabolomics.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/View/GraphPackage/Util.pm
**** ApiDBTuning.PROPERTYTYPE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.PROTEINATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
**** ApiDBTuning.PROTEINSEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/STRING.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/Mitoprot.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/ChloroP.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/IsolateAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/InterPro.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/NcbiBLAST.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/MendelGPI.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/WolfPSORT.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolGeneOrf.pm
**** ApiDBTuning.RFLPGENOTYPES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/rflpIsolateAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/rflpIsolateQueries.xml
**** ApiDBTuning.RNASEQSTATS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDBTuning.SAMPLEDISPLAYINFO
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDBTuning.SAMPLEPROCESS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/rflpIsolateAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/sampleTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/rflpIsolateQueries.xml
**** ApiDBTuning.SAMPLES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/rflpIsolateAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/rflpIsolateQueries.xml
**** ApiDBTuning.SEQUENCEPIECECLOSURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
**** ApiDBTuning.SIMILARITYSPANLOCATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDBTuning.SNPATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/snpQueries.xml
**** ApiDBTuning.SNPATTRIBUTESDOTS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/snpChipQueries.xml
**** ApiDBTuning.SNPCHIPATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/snpChipQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/snpChipParams.xml
**** ApiDBTuning.SNPCHIPSTRAINS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** ApiDBTuning.SNPSTRAINS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** ApiDBTuning.SPLICESITETRANSCRIPTS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDBTuning.STRINGDB
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDBTuning.SUBCELLULAR
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDBTuning.TAXONOMY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
**** ApiDBTuning.TAXONSPECIES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** ApiDBTuning.TFBSGENE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDBTuning.TRANSCRIPTATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptSummaryQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/recordParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/.organismParams.xml.swp
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/similarityParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ProfileByEC.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/multipleSeqAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/IsolateAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolGeneOrf.pm
**** ApiDBTuning.TRANSCRIPTCENDISTANCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/.organismParams.xml.swp
**** ApiDBTuning.TRANSCRIPTPATHWAY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/pathwayParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/Model/PathwaysEnrichment.pm
**** ApiDBTuning.TRANSCRIPTSEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/IsolateAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/SequenceRetrievalToolGeneOrf.pm
*** ApiDB
**** ApiDB.AGPPIECE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
**** ApiDB.BLATPROTEINALIGNMENT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDB.CHRCOPYNUMBER
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/genomicQueries.xml
**** ApiDB.COMPOUNDMASSSPECRESULT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
**** ApiDB.COMPOUNDPEAKS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
**** ApiDB.COMPOUNDPEAKSCHEBI
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
**** ApiDB.CRISPRPHENOTYPE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/PhenotypeScore.pm
**** ApiDB.DATASOURCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/organismTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/.organismParams.xml.swp
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonModel/Model/DataSourceList.pm
**** ApiDB.EXTERNALRESOURCEURL
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDB.FEATURELOCATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/orfTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/orfQueries.xml
**** ApiDB.GENEFEATUREPRODUCT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDB.GENEINTERACTION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.GFF3
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDB.LOPITRESULTS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDB.MASSSPECSUMMARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** ApiDB.NAFEATUREHAPLOBLOCK
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/spanQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.NAFEATUREIMAGE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/GeneImage.pm
**** ApiDB.NAFEATUREMETACYCLE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.NAFEATUREPHENOTYPE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDB.NAFEATUREPHENOTYPEMODEL
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDB.OLDANNOTATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.OLDCODINGSEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDB.ONTOLOGYTERMRESULT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDB.ORGANISM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/templates/RnaSeqGbrowseTemplates.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/multipleSeqAlignment.pm
**** ApiDB.PATHWAYREACTIONXREF
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayTableQueries.xml
**** ApiDB.PHENOTYPEGROWTHRATE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/PhenotypeScore.pm
**** ApiDB.PHENOTYPEMODEL
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDB.PHENOTYPEMUTANTS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.PHENOTYPERESULT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** ApiDB.PHENOTYPESCORE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/PhenotypeScore.pm
**** ApiDB.PHYLOGENETICPROFILE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.PUBCHEMSUBSTANCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
**** ApiDB.RFLPGENOTYPE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/rflpIsolateTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/rflpIsolateParams.xml
**** ApiDB.SEQEDIT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDB.SEQUENCEVARIATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipTableQueries.xml
**** ApiDB.SPLICESITEFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.SPLICESITEGENES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** ApiDB.SYNTENICGENE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** ApiDB.SYNTENY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
**** ApiDB.TRANSCRIPTLOCATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** ApiDB.TRANSCRIPTPRODUCT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
*** chEBI
**** chEBI.CHEMICAL_DATA
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
**** chEBI.COMPOUNDS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
**** chEBI.DEFAULT_STRUCTURES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundAttributeQueries.xml
**** chEBI.NAMES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundAttributeQueries.xml
**** chEBI.STRUCTURES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundAttributeQueries.xml
*** Core
**** Core.ALGORITHM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetPresenters/ToxoDB.xml
**** Core.ALGORITHMINVOCATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/sql/installReflowSchema.sql
**** Core.TABLEINFO
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml

  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
*** DoTS
**** DoTS.AAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
    - [ ] Uniprot
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] gene_dbrefs
    - [ ] 3dpreds
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] GenesWithStructurePrediction
**** DoTS.AALOCATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [ ] LowComplexity
    - [ ] SignalP
    - [ ] exportpred
    - [ ] TMHMM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] UnifiedMassSpec 
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] TMHMM
    - [ ] signalp
    - [ ] lowcomplexity
**** DoTS.AASEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [ ] LowComplexity
    - [ ] exportpred
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] UnifiedMassSpec     
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] LowComplexity    
**** DoTS.AASEQUENCEENZYMECLASS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
    - [ ] pathway plot
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] ECNumbers
    - [ ] ECNumbersInferred      
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] GenesByECNumber
    - [ ] GenesByECNumberDirect
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
    - [ ] ECNumberList
    - [ ] ECNumberSource
    - [ ] ECNumberAllSources
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/PathwayGeneraData.pm
    - [ ] pathway plot
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ProfileByEC.pm
    - [ ] pathway plot
**** DoTS.AASEQVARIATION                                   :SteveF:DELETE:
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/WDK/Model/GDUtil/Transducer/GUSAASequenceTransducer.pm
    - [ ] DELETE
**** DoTS.BINDINGSITEFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] Binding Site Feature
**** DoTS.BLATALIGNMENT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] piggyBac transposable elements
    - [ ] generic end feature
    - [ ] dbest
    - [ ] old gene models ???
    - [ ] alignment:sequences (maxicircle, ...)
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estTableQueries.xml
    - [ ] EST Alignment
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanTableQueries.xml
    - [ ] ESTs
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/estQueries.xml
    - [ ] ESTs by location
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
    - [ ] withchrom est
**** DoTS.CHROMOSOMEELEMENTFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] haplotype block feature (eqtl)
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/spanQueries.xml
    - [ ] eqtl segments
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] eqtl segments    
**** DoTS.DBREFAAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
    - [ ] Uniprot
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] gene_dbrefs
    - [ ] 3dpreds
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] Reagents
    - [ ] StructurePrediction
**** DoTS.DBREFNAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] Metabolic Pathways
    - [ ] Antibody
    - [ ] gene_dbrefs
    - [ ] FungiOrgLinkouts
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
    - [ ] where reviewed??  what is this?
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] MetabolicPathways Haggai
    - [ ] Reagents (Crypto??) 
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
    - [ ] Metabolic Pathways
**** DoTS.DBREFNASEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
    - [ ] db refs
**** DoTS.DOMAINFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [X] Interpro
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [X] Interpro
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [X] Interpro
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
    - [X] Interpro
**** DoTS.EPITOPEFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] GenesWithEpitopes
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/WDK/Model/GDUtil/Transducer/GUSAASequenceTransducer.pm
    - [ ] probably unused??
**** DoTS.EST
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
    - [ ] ESTs
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] ESTs    
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estAttributeQueries.xml
    - [ ] ESTs    
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estTableQueries.xml
    - [ ] ESTs    
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/dynSpanTableQueries.xml
    - [ ] ESTs    
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
    - [ ] ESTs    

**** DoTS.EXTERNALNASEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/spanQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/genomicQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** DoTS.GENEFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] repeat region
    - [ ] alternate gene models
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] Preferred Products
    - [ ] GeneId
    - [ ] ProteinDatabase
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
    - [ ] gene overlap
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
    - [ ] withGff genes
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/WDK/Model/GDUtil/Transducer/ExpressionGraph.pm
    - [ ] Steve
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/GeneImage.pm
    - [ ] Gene Image (Cellular location??)
**** DoTS.GOASSOCINSTEVIDCODE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] PreferredProducts
    - [ ] AlternativeProducts
**** DoTS.ISOLATEFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
**** DoTS.ISOLATESOURCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
**** DoTS.LIBRARY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] dbest
**** DoTS.LOWCOMPLEXITYAAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [ ] Low Complexity
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] Low Complexity    
**** DoTS.LOWCOMPLEXITYNAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] Low Complexity    
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
    - [ ] Low Complexity        
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/WDK/Model/GDUtil/Transducer/GUSGenomicContextTransducer.pm
    - [ ] Steve
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/WDK/Model/GDUtil/Transducer/GUSGenomicSeqTransducer.pm
    - [ ] Steve    
**** DoTS.MASSSPECFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] Mass Spec
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
    - [ ] ms_assay
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/WDK/Model/GDUtil/Transducer/GUSAASequenceTransducer.pm
    - [ ] Steve    
**** DoTS.MOTIFAASEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] GenesWithEpitopes
**** DoTS.NAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] Various Queries (ok if we dump these as files)
**** DoTS.NAFEATURECOMMENT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] Notes
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
    - [ ] Repeats
**** DoTS.NALOCATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] Various Queries (ok if we dump these as files)
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/spanQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** DoTS.NASEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/genomicQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/HtsSNPAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/IsolateAlignment.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/CgiApp/MultipleAlignmentMercatorMavid.pm
**** DoTS.NASEQUENCEREF
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
**** DoTS.REPEATS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** DoTS.RNAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] trnas
**** DoTS.RNAFEATUREEXON
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] gene models
**** DoTS.SCAFFOLDGAPFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/WDK/Model/GDUtil/Transducer/GUSGenomicSeqTransducer.pm
    - [ ] Steve    
**** DoTS.SECONDARYSTRUCTURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** DoTS.SECONDARYSTRUCTURECALL
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** DoTS.SIGNALPEPTIDEFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
**** DoTS.SIMILARITY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] popset
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
    - [ ] popset
**** DoTS.SNPFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
    - [ ] barcode snps
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/snpChipQueries.xml
**** DoTS.SPLICEDNASEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] Sequences table
**** DoTS.STS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
    - [ ] Microsatellite
**** DoTS.TANDEMREPEATFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
**** DoTS.TRANSCRIPT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [ ] get_feature_by_name (i dont' think this is used anymore???)
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
    - [ ] test count query
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] TMHMM
    - [ ] LowComplexity
    - [ ] PreferredProducts
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] GiardiaGenesByDifferentialExpression (unused???)
**** DoTS.TRANSLATEDAAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [ ] get_feature_by_name (i dont' think this is used anymore???)
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] TMHMM
    - [ ] LowComplexity
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
    - [ ] Reagents
**** DoTS.TRANSLATEDAASEQUENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [ ] get_feature_by_name (i dont' think this is used anymore???)
    - [ ] get_sequence (i dont' think this is used anymore???)      
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] TMHMM
**** DoTS.TRANSMEMBRANEAAFEATURE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
    - [ ] TMHMM    
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
    - [ ] TMHMM    
**** DoTS.TRANSPOSABLEELEMENT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
*** EDA
**** EDA.ATTRIBUTE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** EDA.ENTITYATTRIBUTES
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** EDA.ENTITYTYPE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** EDA.ENTITYTYPEGRAPH
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** EDA.STUDY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
*** hmdb
**** hmdb.COMPOUNDS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
*** Platform
**** Platform.REPORTER
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** Platform.REPORTERLOCATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
*** Results
**** Results.COMPOUNDMASSSPEC
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
**** Results.NAFEATUREDIFFRESULT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
**** Results.NAFEATUREEXPRESSION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/profileGraphs.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/SenseAntisenseX.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/SenseAntisenseY.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/RNASeq.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/Proteomics/NonRatio.pm
**** Results.NAFEATUREHOSTRESPONSE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** Results.REPORTERINTENSITY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** Results.SEGMENTRESULT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
**** Results.SEQVARIATION
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpChipTableQueries.xml
*** SRes
**** SRes.BIBLIOGRAPHICREFERENCE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
**** SRes.CONTACT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estAttributeQueries.xml
**** SRes.DBREF
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** SRes.ENZYMECLASS
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/PathwayGeneraData.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/Model/CannedQuery/ProfileByEC.pm
**** SRes.EXTERNALDATABASE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml

  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml

  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/pathwayParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/rnaSeqTemplates.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/spliceSitesTemplates.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
**** SRes.EXTERNALDATABASERELEASE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/proteinQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml

  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneAttributeQueries.xml

  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/snpTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/commentTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/pathwayParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/rnaSeqTemplates.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/spliceSitesTemplates.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
**** SRes.GENETICCODE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
**** SRes.ONTOLOGYRELATIONSHIP
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
**** SRes.ONTOLOGYSYNONYM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** SRes.ONTOLOGYTERM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicSummaryQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/estAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/.organismParams.xml.swp
**** SRes.PATHWAY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/pathwayAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/pathwayQueries.xml
**** SRes.TAXON
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/genomicQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
**** SRes.TAXONNAME
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/datasetClass/classes.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/transcriptAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/genomicAttributeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/datasetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/.organismParams.xml.swp
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonModel/Model/DataSourceList.pm
*** Study
**** Study.CHARACTERISTIC
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
**** Study.OUTPUT
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** Study.PROTOCOLAPPNODE
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/compoundTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/genomicQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/RNASeq.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/Proteomics/NonRatio.pm
**** Study.PROTOCOLAPPPARAM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
**** Study.PROTOCOLPARAM
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
**** Study.STUDY
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/datasetRecords.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/sampleTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/compoundParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/organismParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/rnaSeqTemplates.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/RNASeq.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/Proteomics/NonRatio.pm
**** Study.STUDYBIBREF
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
**** Study.STUDYLINK
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/dataPlotter/queries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/xml/jbrowse/genomeQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/popsetTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/geneTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/records/sampleTableQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/compoundQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/popsetQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/queries/geneQueries.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/popsetParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/sharedParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/wdk/model/questions/params/geneParams.xml
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/dst/expression.dst
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/EbrcWebsiteCommon/View/GraphPackage/Util.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/RNASeq.pm
  - /var/www/PlasmoDB/plasmo.jbrestel/gus_home/lib/perl/ApiCommonWebsite/View/GraphPackage/Templates/Proteomics/NonRatio.pm
    
